-- 1
-- ANIMAL_INS 테이블에서 * 전체를 선택한다. 그리고 ANIMAL_ID 로 정렬한다.
SELECT * FROM ANIMAL_INS
    ORDER BY ANIMAL_ID

-- 2
-- 역순 정렬
SELECT NAME, DATETIME FROM ANIMAL_INS
    ORDER BY ANIMAL_ID DESC
    
-- 3
-- 조건 설정
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS
    WHERE INTAKE_CONDITION = 'Sick'
    
-- 4
-- 조건 설정
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS
    WHERE INTAKE_CONDITION != 'Aged'

-- 5
-- 정렬
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS
    ORDER BY ANIMAL_ID

-- 6
-- 2개의 조건으로 정렬
SELECT ANIMAL_ID, NAME, DATETIME FROM ANIMAL_INS
    ORDER BY NAME, DATETIME DESC

-- 7
-- 상위 n개 레코드
SELECT NAME FROM ANIMAL_INS
    ORDER BY DATETIME
        LIMIT 1
